// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgWbwnhKpW49duCdwmUFSOWyrzxg9jL5c',
    appId: '1:837238016242:web:829d969e97921b119ae86b',
    messagingSenderId: '837238016242',
    projectId: 'notas-08',
    authDomain: 'notas-08.firebaseapp.com',
    storageBucket: 'notas-08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmx6TkWzzEzEJ6xnplVKqYrwkGGplQmf4',
    appId: '1:837238016242:android:173ab13f59ac774d9ae86b',
    messagingSenderId: '837238016242',
    projectId: 'notas-08',
    storageBucket: 'notas-08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOnlo6ozJW3MHpTA-waw_Q_eY4RhVfomw',
    appId: '1:837238016242:ios:2da6fb06b1146e9e9ae86b',
    messagingSenderId: '837238016242',
    projectId: 'notas-08',
    storageBucket: 'notas-08.appspot.com',
    iosBundleId: 'com.example.notas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOnlo6ozJW3MHpTA-waw_Q_eY4RhVfomw',
    appId: '1:837238016242:ios:2da6fb06b1146e9e9ae86b',
    messagingSenderId: '837238016242',
    projectId: 'notas-08',
    storageBucket: 'notas-08.appspot.com',
    iosBundleId: 'com.example.notas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgWbwnhKpW49duCdwmUFSOWyrzxg9jL5c',
    appId: '1:837238016242:web:fa9f3ef7981d35639ae86b',
    messagingSenderId: '837238016242',
    projectId: 'notas-08',
    authDomain: 'notas-08.firebaseapp.com',
    storageBucket: 'notas-08.appspot.com',
  );
}
